version: '2'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
  backend-test:
    image: backend-test
    restart: unless-stopped
    environment:
      - HTTP_PORT=3000
    ports:
      - "0.0.0.0:3000:3000"
    links:
      - mongo
    depends_on:
      - mongo